plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# Докстринги не требуем
Style/Documentation:
  Enabled: false

# Длину строк смягчаем и не проверяем config/ и test/
Layout/LineLength:
  Max: 140
  AllowedPatterns:
    - '^#'        # не ругаться на длинные комментарии
  Exclude:
    - 'config/**/*'
    - 'test/**/*'

# Кавычки в Rakefile не трогаем
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'Rakefile'

# Однострочные пространства имён — ок
Style/ClassAndModuleChildren:
  Enabled: false

# Метрики сложности/длины сейчас не навязываем
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/initializers/**/*'
    - 'config/environments/**/*'
    - 'lib/tasks/**/*'
    - 'Rakefile'

# Формат аргументов/скобок — не проверяем в конфигах
Layout/ArgumentAlignment:
  Exclude:
    - 'config/environments/**/*'
Layout/MultilineMethodCallBraceLayout:
  Exclude:
    - 'config/**/*'
    - 'config/initializers/**/*'

# Лямбды из simple_form_bootstrap — оставить как есть
Layout/SpaceInLambdaLiteral:
  Enabled: false

# Нет требования else в production.rb
Style/MissingElse:
  Exclude:
    - 'config/environments/production.rb'
