databases:
  - name: rails-project-64-db
    plan: free

services:
  - type: web
    name: rails-project-64
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: ./bin/render-start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-project-64-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: WEB_CONCURRENCY
        value: "2"
